export const FETCH_GET_DISHES_MENU_START = "FETCH_GET_DISHES_MENU_START";
export const FETCH_GET_DISHES_MENU_SUCCESS = "FETCH_GET_DISHES_MENU_SUCCESS";
export const FETCH_GET_DISHES_MENU_ERROR = "FETCH_GET_DISHES_MENU_ERROR";