export const FETCH_ADD_ROL_START = "FETCH_ADD_ROL_START";
export const FETCH_ADD_ROL_SUCCESS = "FETCH_ADD_ROL_SUCCESS";
export const FETCH_ADD_ROL_ERROR = "FETCH_ADD_ROL_ERROR";

export const FETCH_UPDATE_ROL_START = "FETCH_UPDATE_ROL_START";
export const FETCH_UPDATE_ROL_SUCCESS = "FETCH_UPDATE_ROL_SUCCESS";
export const FETCH_UPDATE_ROL_ERROR = "FETCH_UPDATE_ROL_ERROR";

export const FETCH_DEL_ROL_START = "FETCH_DEL_ROL_START";
export const FETCH_DEL_ROL_SUCCESS = "FETCH_DEL_ROL_SUCCESS";
export const FETCH_DEL_ROL_ERROR = "FETCH_DEL_ROL_ERROR";

export const FETCH_GET_ROLS_START = "FETCH_GET_ROLS_START";
export const FETCH_GET_ROLS_SUCCESS = "FETCH_GET_ROLS_SUCCESS";
export const FETCH_GET_ROLS_ERROR = "FETCH_GET_ROLS_ERROR";

export const SHOW_FORM_ROL = "SHOW_FORM_ROL";

export const ROL_SELECTED = "ROL_SELECTED";

/**
 * ------------------
 * PERMISSIONS BY ROL
 * ------------------
 */
export const SHOW_FORM_PERMISSIONS = "SHOW_FORM_PERMISSIONS";

export const FETCH_UPDATE_PERMISSIONS_START = "FETCH_UPDATE_PERMISSIONS_START";
export const FETCH_UPDATE_PERMISSIONS_SUCCESS = "FETCH_UPDATE_PERMISSIONS_SUCCESS";
export const FETCH_UPDATE_PERMISSIONS_ERROR = "FETCH_UPDATE_PERMISSIONS_ERROR";

