export const FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_START = "FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_START";
export const FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_SUCCESS = "FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_SUCCESS";
export const FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_ERROR = "FETCH_ADD_ORDER_SUMARY_TOTAL_BY_CLIENT_ERROR";
export const FETCH_REP_SALES_START = "FETCH_REP_SALES_START";
export const FETCH_REP_SALES_SUCCESS = "FETCH_REP_SALES_SUCCESS";
export const FETCH_REP_SALES_ERROR = "FETCH_REP_SALES_ERROR";